# Generated by Django 5.2 on 2025-05-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0003_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(default='Dirección no especificada'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.TextField(default='Dirección no especificada'),
        ),
    ]
