# Generated by Django 5.2 on 2025-05-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0007_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='dificultad',
        ),
    ]
