# Generated by Django 5.2 on 2025-05-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0008_remove_ticket_dificultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_imagen', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_ticket.ticket')),
            ],
        ),
    ]
