# Generated by Django 5.2 on 2025-05-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0009_imagenticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, '1 - Muy Malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='app_ticket.ticket')),
            ],
        ),
    ]
