# Generated by Django 5.2 on 2025-05-28 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0010_evaluaciontecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolucionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_imagen', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_ticket.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenTicket',
        ),
    ]
