# Generated by Django 5.2 on 2025-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0011_solucionticket_delete_imagenticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucionticket',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='solucion_tickets'),
        ),
    ]
