# Generated by Django 5.2 on 2025-05-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0013_remove_usuario_rol_usuario_usuarios_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('supervisor', 'Supervisor')], default='tecnico', max_length=20),
        ),
    ]
