# Generated by Django 5.2 on 2025-05-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0014_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
