# Generated by Django 5.2 on 2025-06-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0015_remove_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('atencion', 'Atencion'), ('supervisor', 'Supervisor')], default='tecnico', max_length=20),
        ),
    ]
