<<<<<<< HEAD
# Generated by Django 5.2 on 2025-06-03 03:04
=======
# Generated by Django 5.2 on 2025-06-03 02:43
>>>>>>> 9739e3973bfa00f3c1b318c37cb92aaf7f9daf19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0016_alter_ticket_fecha_cierre_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
