# Generated by Django 5.2 on 2025-06-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0017_alter_ticket_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anydesk_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
