# Generated by Django 5.2 on 2025-06-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0018_cliente_anydesk_empresa_cliente_empresa_cliente_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
