# Generated by Django 5.2 on 2025-06-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0020_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
