# Generated by Django 5.2 on 2025-06-12 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0021_delete_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solucionticket',
            name='ruta_imagen',
        ),
        migrations.AlterField(
            model_name='solucionticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to='app_ticket.ticket'),
        ),
        migrations.CreateModel(
            name='ImagenSolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='solucion_tickets')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_ticket.solucionticket')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
