# Generated by Django 5.2 on 2025-06-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0022_remove_solucionticket_ruta_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='app_ticket.empresa'),
        ),
    ]
