# Generated by Django 5.2 on 2025-06-17 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0023_alter_sucursal_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='app_ticket.sucursal'),
        ),
        migrations.AlterField(
            model_name='evaluaciontecnico',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion', to='app_ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='imagensolucion',
            name='solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes', to='app_ticket.solucionticket'),
        ),
        migrations.AlterField(
            model_name='solucionticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soluciones', to='app_ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='app_ticket.categoria'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='app_ticket.cliente'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to='app_ticket.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_ticket.departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuarios',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
