# Generated by Django 5.2 on 2025-07-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0023_alter_departamento_sucursal_alter_sucursal_empresa_and_more'),
        ('app_ticket', '0024_alter_departamento_sucursal_and_more'),
    ]

    operations = [
    ]
