# Generated by Django 5.2 on 2025-07-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0025_merge_20250702_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuales', to='app_ticket.empresa')),
            ],
        ),
    ]
