# Generated by Django 5.2 on 2025-05-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
    ]
